/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.DatabaseConnection;
import entity.Platillos;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author octavio
 */
public class AgregarPlatillos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPlatillos
     */
    private DatabaseConnection servicio;
    private long idEstablecimiento;
    public AgregarPlatillos(long idEstablecimiento) {
        initComponents();
        this.idEstablecimiento = idEstablecimiento;
        servicio = new DatabaseConnection();
    }
    public AgregarPlatillos() {
        initComponents();
        servicio = new DatabaseConnection();
    }
    
      public JPanel getFondo() {
        return Background ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Signo = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        tfNombrePlatillo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescripcion = new javax.swing.JTextArea();
        label2 = new java.awt.Label();
        buttonAgregar = new java.awt.Button();
        label3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(27, 53, 164));
        Background.setMaximumSize(new java.awt.Dimension(5000, 2147483647));
        Background.setMinimumSize(new java.awt.Dimension(480, 480));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Signo.setBackground(new java.awt.Color(1, 1, 1));
        Signo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Signo.setForeground(new java.awt.Color(254, 254, 254));
        Signo.setText("$");
        Background.add(Signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 20, 30));

        tfPrecio.setBackground(new java.awt.Color(1, 1, 1));
        tfPrecio.setForeground(new java.awt.Color(254, 254, 254));
        tfPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPrecio.setText("Precio");
        tfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecioActionPerformed(evt);
            }
        });
        Background.add(tfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 110, 30));

        tfNombrePlatillo.setText("Escribe el nombre del platillo");
        tfNombrePlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombrePlatilloActionPerformed(evt);
            }
        });
        Background.add(tfNombrePlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 520, 50));

        tfDescripcion.setColumns(20);
        tfDescripcion.setRows(5);
        jScrollPane1.setViewportView(tfDescripcion);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 520, 120));

        label2.setForeground(new java.awt.Color(254, 254, 254));
        label2.setText("Nombre del platillo");
        Background.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 20));

        buttonAgregar.setBackground(new java.awt.Color(255, 0, 0));
        buttonAgregar.setForeground(new java.awt.Color(254, 254, 254));
        buttonAgregar.setLabel("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });
        Background.add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 90, 30));

        label3.setForeground(new java.awt.Color(254, 254, 254));
        label3.setText("Descripción");
        Background.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 80, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuchilleria (1).png"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1000, 80));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar platillo");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioActionPerformed

    private void tfNombrePlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombrePlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombrePlatilloActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        // TODO add your handling code here:
        System.out.println(tfDescripcion.getText());
        if(tfNombrePlatillo.getText().equals("") || tfDescripcion.getText().equals("") || tfPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Llene todos los campos.");
        }
        else{
            if(servicio.Conectar()){
                nuevoPlatillo(tfNombrePlatillo.getText(),Float.parseFloat(tfPrecio.getText()),tfDescripcion.getText());
            }
            else {
                JOptionPane.showMessageDialog(null, "Error al conectarse a la base de datos.");
            }
            servicio.Desconectar();
        }
    }//GEN-LAST:event_buttonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlatillos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Signo;
    private java.awt.Button buttonAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextArea tfDescripcion;
    private javax.swing.JTextField tfNombrePlatillo;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
    public void nuevoPlatillo(String nombrePlatillo,float Precio,String Descripcion)
    { 
        Platillos platillo = new Platillos(servicio);
        platillo.setIdPlatillo(0);
        platillo.setNombrePlatillo(nombrePlatillo);
        platillo.setPrecio(Precio);
        platillo.setDescripcion(Descripcion);
        platillo.setIdEstablecimiento(idEstablecimiento);
        if(platillo.crearPlatillo(platillo))
        {
            nuevoPlatillo();
        }
        else
        {
            marcaError();
        }
    }
    private void nuevoPlatillo()
    {
        JOptionPane.showMessageDialog(null, "Platillo Creado Correctamente.");
        //this.dispose();
    }
    private void marcaError()
    {
        JOptionPane.showMessageDialog(null, "¡ERROR! El platillo no se pudo crear.");
    }
}
