/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import entity.establecimiento;
import clases.DatabaseConnection;
import entity.usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author octavio
 */
public class HomeCliente extends javax.swing.JFrame {
    /**
     * Creates new form P_HomeCliente
     */
    public static ArrayList <establecimiento> listEstablecimientos = new ArrayList<>();
    DatabaseConnection servicio;
    public static DefaultTableModel dtm = new DefaultTableModel();
    public static long idEstablecimiento;
    
    private long idUsuario;
    public HomeCliente() {
        initComponents();
    }
    public HomeCliente(long idUsuario) {
        this.idUsuario = idUsuario;
        initComponents();
        listarEstablecimientos();
        usuario nUsuario = new usuario();
        nUsuario=servicio.listOneUsuario(idUsuario);
        Usuario.setText(nUsuario.getNombres()+" "+nUsuario.getApellidoPaterno()+" "+nUsuario.getApellidoMaterno());
    }
    
    public void listarEstablecimientos(){
        servicio = new DatabaseConnection();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        String[] titulo = new String[]{"Nombre del Establecimiento","Dirección","Telefono"};
        dtm.setColumnIdentifiers(titulo);
        TablaEstablecimiento.setModel(dtm);
        
        if(servicio.Conectar()){
            listEstablecimientos = servicio.listEstablecimiento();
        }
        else
            JOptionPane.showMessageDialog(null, "Error al conectar");
        
        if(listEstablecimientos.size()>0){
            for(establecimiento reco:listEstablecimientos)
                addEstablecimiento(reco);
        }else
            sinEstablecimiento();
        
    }
        public void addEstablecimiento(establecimiento establecimiento_p){
       dtm.addRow(new Object[]{
           establecimiento_p.getNombreEstablecimiento(), establecimiento_p.getDireccion(), String.valueOf(establecimiento_p.getTelefono())
       });
    }
    
    public int seleccionado(){
        int ref = TablaEstablecimiento.getSelectedRow();
        return ref;
    }
    
    public void visualizarMenu(long idEstablecimiento){
        Reservacion reserva = new Reservacion(idEstablecimiento,this.idUsuario);
        reserva.setVisible(true);
    }
    
    public void sinEstablecimiento(){
        JOptionPane.showMessageDialog(null, "No hay establecimientos");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        tituloPlace = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEstablecimiento = new javax.swing.JTable();
        ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(254, 254, 254));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPlace.setBackground(new java.awt.Color(27, 53, 164));
        tituloPlace.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setForeground(new java.awt.Color(254, 254, 254));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenta (2).png"))); // NOI18N
        Usuario.setText("Usuario");
        tituloPlace.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, -2, 230, 80));

        Salida.setForeground(new java.awt.Color(253, 251, 251));
        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion (1).png"))); // NOI18N
        Salida.setText("Salir");
        Salida.setBorderPainted(false);
        Salida.setContentAreaFilled(false);
        Salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalidaMouseClicked(evt);
            }
        });
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        tituloPlace.add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 120, 80));

        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoLettras.png"))); // NOI18N
        tituloPlace.add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1190, 80));

        Background.add(tituloPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        TablaEstablecimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEstablecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEstablecimientoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaEstablecimiento);

        Background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 130, 1010, 280));

        ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoOp1.jpg"))); // NOI18N
        Background.add(ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaActionPerformed
    
    //Aquí sería el seleccionarEstablecimiento().
    private void TablaEstablecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEstablecimientoMouseClicked
        // TODO add your handling code here:
        int i =  evt.getY()/TablaEstablecimiento.getRowHeight();
        idEstablecimiento = listEstablecimientos.get(i).getIdEstablecimiento();
        if(servicio.listarPlatillosValidos(idEstablecimiento).size()>0)
            visualizarMenu(idEstablecimiento); 
        else
            JOptionPane.showMessageDialog(null, "No hay platillos");
    }//GEN-LAST:event_TablaEstablecimientoMouseClicked

    private void SalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaMouseClicked
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ImgFondo;
    private javax.swing.JButton Salida;
    private javax.swing.JTable TablaEstablecimiento;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel Usuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel tituloPlace;
    // End of variables declaration//GEN-END:variables
}
