/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.DatabaseConnection;
import clases.validacion;
import javax.swing.JPanel;
import entity.Platillos;
import javax.swing.JOptionPane;
/**
 *
 * @author octavio
 */
public class HomeVendedor extends javax.swing.JFrame {

    /**
     * Creates new form HomeVendedor
     */
    private long idEstablecimiento;
    private long idUsuario;
    private DatabaseConnection servicio;
    public HomeVendedor(long idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        System.out.println("idUsuario: "+this.idUsuario);
        this.servicio = new DatabaseConnection();
        if(servicio.Conectar()){
                this.idEstablecimiento = servicio.getEstablecimientoByUsuario(this.idUsuario);
                System.out.println("idEstablecimiento: "+ this.idEstablecimiento);
            }
            else {
                JOptionPane.showMessageDialog(null, "Error al conectarse a la base de datos.");
            }
            servicio.Desconectar();
        
        ListadoPlatillos listado = new ListadoPlatillos(this.idEstablecimiento);
        MostrarPanel(listado.getFondo());
    }
    public HomeVendedor() {
        initComponents();
        
        ListadoPlatillos listado = new ListadoPlatillos();
        MostrarPanel(listado.getFondo());
    }
    
      private void MostrarPanel(JPanel p){
        p.setSize(1000, 480);
        p.setLocation(0, 0);
        Content.removeAll();
        Content.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        Content.revalidate();
        Content.repaint();
    }
    /*public void listarPlatillo()
    {
        platillo nPlatillo=new platillo();
        if(servicio.Conectar())
        {
          nPlatillo=servicio.getPlatillosByEstablecimiento(1);
            System.out.println("PLATILLO: "+nPlatillo);  
        }
        
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnInformacion = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(254, 254, 254));
        Background.setForeground(new java.awt.Color(254, 254, 254));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 53, 164));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setForeground(new java.awt.Color(254, 254, 254));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenta (2).png"))); // NOI18N
        Usuario.setText("Usuario");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, -2, 130, 80));

        Salida.setForeground(new java.awt.Color(253, 251, 251));
        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion (1).png"))); // NOI18N
        Salida.setText("Salir");
        Salida.setBorderPainted(false);
        Salida.setContentAreaFilled(false);
        Salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalidaMouseClicked(evt);
            }
        });
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        jPanel1.add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 120, 80));

        BtnAgregar.setBackground(new java.awt.Color(1, 1, 1));
        BtnAgregar.setForeground(new java.awt.Color(254, 254, 254));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 30));

        BtnInformacion.setBackground(new java.awt.Color(1, 1, 1));
        BtnInformacion.setForeground(new java.awt.Color(254, 254, 254));
        BtnInformacion.setText("Información");
        BtnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 130, 30));

        BtnListar.setBackground(new java.awt.Color(1, 1, 1));
        BtnListar.setForeground(new java.awt.Color(254, 254, 254));
        BtnListar.setText("Listar");
        BtnListar.setActionCommand("Platillos");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, 130, 30));

        BtnActualizar.setBackground(new java.awt.Color(1, 1, 1));
        BtnActualizar.setForeground(new java.awt.Color(254, 254, 254));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 130, 30));

        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoLettras.png"))); // NOI18N
        jPanel1.add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1190, 80));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 1000, 480));

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed

    }//GEN-LAST:event_SalidaActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        AgregarPlatillos platillos = new AgregarPlatillos (this.idEstablecimiento);
        MostrarPanel (platillos.getFondo());
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInformacionActionPerformed
        InformacionVendedor informacion = new InformacionVendedor(this.idEstablecimiento);
        MostrarPanel (informacion.getFondo());
    }//GEN-LAST:event_BtnInformacionActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        ListadoPlatillos listado = new ListadoPlatillos(this.idEstablecimiento);
        MostrarPanel(listado.getFondo());
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        ActualizarMenu menu = new ActualizarMenu(this.idEstablecimiento);
        MostrarPanel(menu.getFondo());
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void SalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaMouseClicked
        // TODO add your handling code here:
        //Salida
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeVendedor().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnInformacion;
    private javax.swing.JButton BtnListar;
    private javax.swing.JPanel Content;
    private javax.swing.JButton Salida;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //public void 
}
